# target: dependencies
# 'taget' can be a object file or a tag.
# 'dependencies' are some files which are needed by creating 'target'.

all: 
	g++ Main.cpp BinoModel.h BinoModel.cpp -std=c++11 -O1 -o Main
clean:
	rm -i Main